// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Foundation;

namespace TeaTimer
{
    public partial class TeaViewController : NSViewController
    {
		public TeaViewController (IntPtr handle) : base (handle)
		{	
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			// Do any additional setup after loading the view.
		}

		public override NSObject RepresentedObject
		{
			get => base.RepresentedObject;
            // Update the view, if already loaded.
            set => base.RepresentedObject = value;
		}
	}
}
