// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Foundation;

namespace TeaTimer
{
    public partial class TeaViewController : NSViewController
    {
        #region Computed Properties
        public TeaModel Tea { get; set; }
        #endregion

        #region Constructors
        public TeaViewController (IntPtr handle) : base (handle)
		{	
		}
        #endregion

        #region Override Methods
        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            // Do any additional setup before loading the view.
            if (Tea != null)
            {
                TeaTextField.StringValue = Tea.Name;
                SteepTimeTextField.StringValue = Tea.SteepTime.ToString();
                BrewTempTextField.StringValue = Tea.BrewTemp.ToString();
            }
        }

        public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			// Do any additional setup after loading the view.
		}

		public override NSObject RepresentedObject
		{
			get => base.RepresentedObject;
            // Update the view, if already loaded.
            set => base.RepresentedObject = value;
		}
        #endregion
    }
}
